services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
#      SPRING_DATASOURCE_USERNAME: myuser
#      SPRING_DATASOURCE_PASSWORD: secret
#    depends_on:
#      - postgres
#      - mockserver
#      - redis

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  mockserver:
    image: mockserver/mockserver
    ports:
      - 1080:1080
    command: -logLevel INFO

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'